// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eLxt-S8huCOagip1_d9_gxcpZGndw_U',
    appId: '1:196004541565:web:b872e8e5e1e6a3e3a3ad14',
    messagingSenderId: '196004541565',
    projectId: 'study-app-1d6be',
    authDomain: 'study-app-1d6be.firebaseapp.com',
    storageBucket: 'study-app-1d6be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GKFxTBVsqWevcPjmAgaAqZo0tmm5q18',
    appId: '1:196004541565:android:44f7e0d2afd2e847a3ad14',
    messagingSenderId: '196004541565',
    projectId: 'study-app-1d6be',
    storageBucket: 'study-app-1d6be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtxYUF31DfaWREEaMkOP9U6bXcsiPv1Oc',
    appId: '1:196004541565:ios:74981626eaba41b2a3ad14',
    messagingSenderId: '196004541565',
    projectId: 'study-app-1d6be',
    storageBucket: 'study-app-1d6be.appspot.com',
    iosClientId: '196004541565-iqcb8o3uutgchnq72ok13jmssbs6ihag.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtxYUF31DfaWREEaMkOP9U6bXcsiPv1Oc',
    appId: '1:196004541565:ios:74981626eaba41b2a3ad14',
    messagingSenderId: '196004541565',
    projectId: 'study-app-1d6be',
    storageBucket: 'study-app-1d6be.appspot.com',
    iosClientId: '196004541565-iqcb8o3uutgchnq72ok13jmssbs6ihag.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningapp',
  );
}
